/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
import logica.ControladorEditarLote;
import javax.swing.JOptionPane;
import logica.DatosLote;
import java.util.HashMap;
import java.util.Map;
import logica.Planta; // Asegúrate de importar Planta
import java.util.List;

public class EditarLote extends javax.swing.JFrame {
    private String documento;
    private ControladorEditarLote control;
    private Map<String, String> mapaNombresIDsPlantas; // Nombre -> ID (String)
    private List<Planta> listaPlantasCargadas;
    /**
     * Creates new form EditarLote
     */
    public EditarLote() {
        initComponents();
    }
    
    public EditarLote(String documento) {
        initComponents();
        this.documento = documento;
        this.control = new ControladorEditarLote();
        this.mapaNombresIDsPlantas = new HashMap<>();
        // Inicialmente deshabilitamos la edición y el botón actualizar
        habilitarCampos(false); 
        Txt_id.setEditable(true);
    }
    
    private void habilitarCampos(boolean estado) {
        // Txt_id debe permanecer editable solo para la búsqueda
        Txt_num.setEditable(estado);
        Planta.setEditable(estado);
        Txt_lugar_p.setEditable(estado);
        Txt_area.setEditable(estado);
        Txt_fech_siem.setEditable(estado);
        Txt_fech_elim.setEditable(estado);
        Estado.setEnabled(estado); // Usamos setEnabled para JComboBox
        Txt_num_plan.setEditable(estado);
        Txt_fech_pro_re.setEditable(estado);
        Txt_can_pro_re.setEditable(estado);
        Txt_fech_recolec.setEditable(estado);
        Txt_cant_recolect.setEditable(estado);
        Btn_actualizar.setEnabled(estado);
    }

    private void cargarDatosEnCampos(DatosLote lote) {
        // No cargamos Txt_id ya que el usuario lo ingresó
        Txt_num.setText(lote.getNRO_LOTE());
        Txt_lugar_p.setText(lote.getNRO_REGISTRO_ICA_LUGARP());
        Txt_area.setText(lote.getAREA_DE_LOTE());
        Txt_fech_siem.setText(lote.getFECHA_DE_SIEMBRA());

        // Si la fecha de eliminación o recolección es null, la muestra como cadena vacía
        Txt_fech_elim.setText(lote.getFECHA_DE_ELIMINACION() == null ? "" : lote.getFECHA_DE_ELIMINACION());

        // Seleccionar el estado en el JComboBox
        Estado.setSelectedItem(lote.getESTADO()); 

        Txt_num_plan.setText(lote.getCANTIDAD_DE_PLANTAS());
        Txt_fech_pro_re.setText(lote.getFECHA_PROYEC_RECOLEC());
        Txt_can_pro_re.setText(lote.getCANT_PROYEC_RECOLEC());
        Txt_fech_recolec.setText(lote.getFECHA_RECOLECCION() == null ? "" : lote.getFECHA_RECOLECCION());
        Txt_cant_recolect.setText(lote.getCANT_RECOLECTADA());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_buscar = new javax.swing.JButton();
        Txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_lugar_p = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_area = new javax.swing.JTextField();
        Txt_fech_siem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txt_fech_elim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_num_plan = new javax.swing.JTextField();
        Btn_actualizar = new javax.swing.JButton();
        Btn_cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Txt_fech_pro_re = new javax.swing.JTextField();
        Txt_can_pro_re = new javax.swing.JTextField();
        Txt_fech_recolec = new javax.swing.JTextField();
        Txt_cant_recolect = new javax.swing.JTextField();
        Estado = new javax.swing.JComboBox<>();
        Planta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Actualizar información de mis lotes");

        Btn_buscar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Lote:");

        jLabel4.setText("Número lote:");

        jLabel5.setText("Planta: ");

        jLabel7.setText("Número ICA lugar:");

        jLabel8.setText("Área lote:");

        jLabel9.setText("Fecha siembra:");

        jLabel10.setText("Fecha Eliminación:");

        jLabel11.setText("Estado:");

        jLabel2.setText("Cantidad de plantas:");

        Btn_actualizar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_actualizar.setText("Actualizar");
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        Btn_cancelar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cancelar.setText("Cancelar");
        Btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha pro. Recolección:");

        jLabel12.setText("Cantidad pro Recoleeción:");

        jLabel13.setText("Fecha recolección:");

        jLabel14.setText("Cantidad recolectada:");

        Txt_can_pro_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_can_pro_reActionPerformed(evt);
            }
        });

        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crecimiento", "Espera", "recolectado" }));

        Planta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_num_plan)
                            .addComponent(Txt_fech_elim)
                            .addComponent(Estado, 0, 131, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_lugar_p, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Txt_fech_siem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Planta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Btn_buscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(Btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_fech_pro_re)
                            .addComponent(Txt_can_pro_re)
                            .addComponent(Txt_fech_recolec)
                            .addComponent(Txt_cant_recolect, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Btn_buscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Planta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_lugar_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Txt_fech_siem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_fech_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_num_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_fech_pro_re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Txt_can_pro_re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Txt_fech_recolec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Txt_cant_recolect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_cancelar)
                    .addComponent(Btn_actualizar))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
       String id = Txt_id.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar el ID del lote a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DatosLote lote = control.obtenerLote(id);

    if (lote != null) {
        // 1. Obtener la lista de plantas del objeto DatosLote (la trae el controlador)
        this.listaPlantasCargadas = lote.getListaPlantasDisponibles();
        
        // 2. Limpiar el ComboBox y el mapa auxiliar
        Planta.removeAllItems();
        mapaNombresIDsPlantas.clear();

        String nombrePlantaLoteActual = null;
        
        // 3. Llenar el ComboBox (solo con nombres) y el mapa Nombre -> ID
        if (listaPlantasCargadas != null) {
            for (Planta plantaItem : listaPlantasCargadas) {
                String nombrePlanta = plantaItem.getNombreComun(); // Usamos getNombreComun
                String idPlanta = String.valueOf(plantaItem.getIdPlanta()); // El ID de planta es int, lo convertimos a String
                
                Planta.addItem(nombrePlanta); // Agregamos SOLO el nombre al JComboBox<String>
                mapaNombresIDsPlantas.put(nombrePlanta, idPlanta); // Guardamos la relación
                
                // Si esta planta es la del lote encontrado, guardamos su nombre para seleccionarla
                if (idPlanta.equals(lote.getID_PLANTA())) {
                    nombrePlantaLoteActual = nombrePlanta;
                }
            }
        }
        
        // 4. Cargar el resto de campos
        cargarDatosEnCampos(lote); 
        
        // 5. Seleccionar el nombre de la planta correspondiente al lote
        if (nombrePlantaLoteActual != null) {
             Planta.setSelectedItem(nombrePlantaLoteActual);
        } else if (lote.getID_PLANTA() != null && !lote.getID_PLANTA().isEmpty()) {
             // Caso de seguridad: Si el ID del lote existe, pero el nombre no se encontró
             // Podrías agregar un mensaje o seleccionar el primer elemento.
        }

        habilitarCampos(true);
        Txt_id.setEditable(false);
        Btn_buscar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Lote encontrado. Puede editar los campos.", "Búsqueda Exitosa", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Lote no encontrado o error de ID
        habilitarCampos(false);
        Txt_id.setEditable(true);
        Btn_buscar.setEnabled(true);
        JOptionPane.showMessageDialog(this, "No se encontró un lote con ese ID o el ID no es válido.", "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Btn_buscarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // 1. Recopilar datos de la vista
        String idLote = Txt_id.getText(); 
        String nroLote = Txt_num.getText();

        // Obtener el NOMBRE seleccionado del JComboBox<String>
        String nombrePlantaSeleccionada = (String) Planta.getSelectedItem(); 

        // 🌟 CORRECCIÓN CLAVE: Buscar el ID usando el mapa auxiliar 🌟
        // Si el nombre es válido, obtenemos su ID; si no, es una cadena vacía.
        String idPlanta = mapaNombresIDsPlantas.getOrDefault(nombrePlantaSeleccionada, ""); 

        if (idPlanta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una planta válida.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        // El resto de la recolección de datos sigue igual
        String nroIcaLugar = Txt_lugar_p.getText();
        String areaLote = Txt_area.getText();
        String fechaSiembra = Txt_fech_siem.getText();
        String fechaElim = Txt_fech_elim.getText();
        String estado = (String) Estado.getSelectedItem();
        String cantPlantas = Txt_num_plan.getText();
        String fechaProyRecolec = Txt_fech_pro_re.getText();
        String cantProyRecolec = Txt_can_pro_re.getText();
        String fechaRecoleccion = Txt_fech_recolec.getText();
        String cantRecolectada = Txt_cant_recolect.getText();

        // 2. Crear el objeto DatosLote con el ID de la planta obtenido
        DatosLote lote = new DatosLote(
            idLote, nroLote, idPlanta, nroIcaLugar, areaLote, fechaSiembra, 
            fechaElim, estado, cantPlantas, fechaProyRecolec, 
            cantProyRecolec, fechaRecoleccion, cantRecolectada
        );

        // 3. Llamar al controlador para actualizar
        String mensajeError = control.actualizarLote(lote);

        if (mensajeError == null) {
            JOptionPane.showMessageDialog(this, "Lote actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Regresar al estado inicial
            // Nota: Asegúrate de tener la clase Administrar_lotes para este paso
            this.dispose(); 
            Administrar_lotes menuLotes = new Administrar_lotes(this.documento);
            menuLotes.setVisible(true);
            menuLotes.setLocationRelativeTo(null);

        } else {
            // Muestra el error de validación del controlador
            JOptionPane.showMessageDialog(this, mensajeError, "Error de Actualización", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cancelarActionPerformed
        // Cierra esta ventana
        this.dispose();
        // Abre la otra ventana
        Administrar_lotes menuLotes = new Administrar_lotes(this.documento);
        menuLotes.setVisible(true);
        menuLotes.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cancelarActionPerformed

    private void Txt_can_pro_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_can_pro_reActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_can_pro_reActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JComboBox<String> Planta;
    private javax.swing.JTextField Txt_area;
    private javax.swing.JTextField Txt_can_pro_re;
    private javax.swing.JTextField Txt_cant_recolect;
    private javax.swing.JTextField Txt_fech_elim;
    private javax.swing.JTextField Txt_fech_pro_re;
    private javax.swing.JTextField Txt_fech_recolec;
    private javax.swing.JTextField Txt_fech_siem;
    private javax.swing.JTextField Txt_id;
    private javax.swing.JTextField Txt_lugar_p;
    private javax.swing.JTextField Txt_num;
    private javax.swing.JTextField Txt_num_plan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
