/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
import java.util.List;
import logica.InformePro;

public class InformeProduccion extends javax.swing.JFrame {
    private String documento;
    /**
     * Creates new form InformeProduccion
     */
    public InformeProduccion() {
        initComponents();
        Informe_pro.setEditable(false);
    }
    
    public InformeProduccion(List<InformePro> informe, String documento) {
        initComponents();
        this.documento = documento;
        Informe_pro.setEditable(false);
        
        // Cargar y mostrar los datos del informe
        if (informe != null && !informe.isEmpty()) {
            mostrarDatosInforme(informe);
        } else {
            Informe_pro.setText("========================\nINFORME DE PRODUCCIÓN\n========================\n\nNo se encontraron registros de producción para el Nro ICA especificado.");
        }
        
        this.setTitle("Informe de Producción - Nro ICA: " + (informe.isEmpty() ? "N/A" : informe.get(0).getNombreLugar()));
    }
    
    private void mostrarDatosInforme(List<InformePro> informe) {
        if (informe == null || informe.isEmpty()) {
            return;
        }

        StringBuilder sb = new StringBuilder();
        
        // --- 1. CABECERA GENERAL (Mismo para todos los registros del ICA) ---
        // Se toma la información del primer registro, ya que 'nombreLugar' y 'areaTotal'
        // son los mismos para todos los registros devueltos por la consulta SQL.
        InformePro primerRegistro = informe.get(0);
        
        sb.append("======================== INFORME DE PRODUCCIÓN ========================\n");
        sb.append(String.format("Lugar de producción: %s\n", primerRegistro.getNombreLugar()));
        sb.append(String.format("Área cultivada total: %s m²\n", primerRegistro.getAreaTotal()));
        sb.append("=======================================================================\n\n");


        // --- 2. ENCABEZADOS DE LA TABLA ---
        // Definir anchos para una alineación similar a una tabla/consola.
        int wPlanta = 25;
        int wCantRec = 20;
        int wPromRec = 20;
        int wAreaCult = 15;
        
        // Línea 1 de encabezado
        sb.append(String.format("%-" + wPlanta + "s | %-" + wCantRec + "s | %-" + wPromRec + "s | %-" + wAreaCult + "s\n", 
                "Especie vegetal", 
                "Cantidad recolectada", 
                "Promedio de recolección", 
                "Área del cultivo"));
        
        // Línea separadora
        sb.append("------------------------------------------------------------------------------------------\n");

        // Línea 2 de encabezado (Unidades y Nombres de Campo SQL)
        sb.append(String.format("%-" + wPlanta + "s | %-" + wCantRec + "s | %-" + wPromRec + "s | %-" + wAreaCult + "s\n", 
                "Nombre Común", 
                "Recolec. (Kg)", // Ajustado a Kg o t según el contexto real, pero la consulta dice Cantidad
                "Promedio (Kg/Planta)", 
                "Área (m²)"));
        
        sb.append("------------------------------------------------------------------------------------------\n");

        // --- 3. DATOS DEL INFORME (Iteración por especie) ---
        for (InformePro item : informe) {
            sb.append(String.format("%-" + wPlanta + "s | %-" + wCantRec + "s | %-" + wPromRec + "s | %-" + wAreaCult + "s\n",
                    item.getPlanta(),
                    item.getRecolectado(),
                    item.getPromedio(),
                    item.getAreaCultivo()));
        }

        Informe_pro.setText(sb.toString());
        // Colocamos el scroll al inicio para ver la cabecera
        Informe_pro.setCaretPosition(0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Informe_pro = new javax.swing.JTextArea();
        Btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informe_pro.setColumns(20);
        Informe_pro.setRows(5);
        jScrollPane1.setViewportView(Informe_pro);

        Btn_cancelar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cancelar.setText("Cancelar");
        Btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(Btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cancelarActionPerformed
        this.dispose();
        BuscarInformePro bInfPro = new BuscarInformePro(this.documento);
        bInfPro.setVisible(true);
        bInfPro.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeProduccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JTextArea Informe_pro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
