/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
import logica.InformeEstadoLug;
import logica.ControladorInformeEstado;

public class InformeEstLug extends javax.swing.JFrame {
    private String documento;
    private InformeEstadoLug informe;
    /**
     * Creates new form InformeEstLug
     */
    public InformeEstLug() {
        initComponents();
        Informe_est.setEditable(false);
    }
    
    public InformeEstLug(InformeEstadoLug informe, String documento) {
        initComponents();
        this.documento = documento;
        this.informe = informe;
        Informe_est.setEditable(false);
        // Llamada al método para cargar la información en el JTextArea
        mostrarInformeEnArea(); 
        this.setTitle("Informe de Estado del Lugar de Producción");
    }
    
    private void mostrarInformeEnArea() {
        if (informe == null) {
            Informe_est.setText("ERROR: No se recibió información del informe.");
            return;
        }

        // Crear el formato del informe similar a la imagen proporcionada
        StringBuilder sb = new StringBuilder();
        
        // 1. Título Centrado
        sb.append("=================== INFORME DE ESTADO DE LUGAR DE PRODUCCIÓN ===================\n\n");
        
        // 2. Encabezado principal (Nombre del Lugar y Área Total)
        sb.append(String.format("%-30s %-1s %s\n", "Lugar de Producción:", "", informe.getNombreLugar()));
        sb.append(String.format("%-30s %-1s %s Ha\n", "Área Total para Cultivar:", "", informe.getAreaTotal()));
        sb.append("\n");
        
        // 3. Encabezados de tabla
        String headerFormat = "| %-25s | %-25s | %-25s | %-25s |%n";
        String separator = "-------------------------------------------------------------------------------------------------------------------\n";

        sb.append(separator);
        sb.append(String.format(headerFormat, 
            "Cantidad de predios asociados", 
            "Área restante para cultivar", 
            "Cantidad de lotes actuales", 
            "Área ocupada por los lotes"));
        sb.append(separator);
        
        // 4. Datos del informe
        // Nota: Asegúrate de que los datos numericos del DTO sean formateables (o String)
        sb.append(String.format(headerFormat,
            informe.getPredios(),
            informe.getAreaRestante() + " Ha",
            informe.getLotes(),
            informe.getAreaOcupada() + " Ha"));
        sb.append(separator);
        
        Informe_est.setText(sb.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Informe_est = new javax.swing.JTextArea();
        Btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informe_est.setColumns(20);
        Informe_est.setRows(5);
        jScrollPane1.setViewportView(Informe_est);

        Btn_cancelar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cancelar.setText("Cancelar");
        Btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(Btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cancelarActionPerformed
        this.dispose();
        BuscarInformeEstadoLug bInfEst = new BuscarInformeEstadoLug(this.documento);
        bInfEst.setVisible(true);
        bInfEst.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeEstLug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeEstLug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeEstLug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeEstLug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeEstLug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JTextArea Informe_est;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
