/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
public class MenuPropietario extends javax.swing.JFrame {
    private String documentoPropietario;
    /**
     * Creates new form MenuPropietario
     */
    public MenuPropietario() {
        initComponents();
    }
    
    public MenuPropietario(String documento) {
        this.documentoPropietario = documento; // Almacenar el documento
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Registro_predio = new javax.swing.JButton();
        Btn_ver_predios = new javax.swing.JButton();
        Btn_cerrar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Btn_edit_perfil = new javax.swing.JButton();
        Btn_edit_predio = new javax.swing.JButton();
        Btn_eliminar_predio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 112));
        jLabel1.setText("Bienvenido propietario");

        Btn_Registro_predio.setBackground(new java.awt.Color(51, 153, 0));
        Btn_Registro_predio.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Registro_predio.setText("Registrar predio");
        Btn_Registro_predio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registro_predioActionPerformed(evt);
            }
        });

        Btn_ver_predios.setBackground(new java.awt.Color(51, 153, 0));
        Btn_ver_predios.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ver_predios.setText("Ver predios");
        Btn_ver_predios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ver_prediosActionPerformed(evt);
            }
        });

        Btn_cerrar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cerrar.setText("Cerrar sesión");
        Btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cerrarActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 153, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Ver perfil");

        Btn_edit_perfil.setBackground(new java.awt.Color(51, 153, 0));
        Btn_edit_perfil.setForeground(new java.awt.Color(255, 255, 255));
        Btn_edit_perfil.setText("Editar perfil");
        Btn_edit_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_edit_perfilActionPerformed(evt);
            }
        });

        Btn_edit_predio.setBackground(new java.awt.Color(51, 153, 0));
        Btn_edit_predio.setForeground(new java.awt.Color(255, 255, 255));
        Btn_edit_predio.setText("Editar predios");
        Btn_edit_predio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_edit_predioActionPerformed(evt);
            }
        });

        Btn_eliminar_predio.setBackground(new java.awt.Color(51, 153, 0));
        Btn_eliminar_predio.setForeground(new java.awt.Color(255, 255, 255));
        Btn_eliminar_predio.setText("Borrar predio");
        Btn_eliminar_predio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminar_predioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_ver_predios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Registro_predio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_edit_predio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_edit_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_eliminar_predio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Registro_predio)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_ver_predios)
                    .addComponent(Btn_edit_perfil))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_edit_predio)
                    .addComponent(Btn_eliminar_predio))
                .addGap(18, 18, 18)
                .addComponent(Btn_cerrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Registro_predioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registro_predioActionPerformed
        this.dispose();
        Registro_predio pRegPredio = new Registro_predio(documentoPropietario);
        pRegPredio.setVisible(true);
        pRegPredio.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_Registro_predioActionPerformed

    private void Btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cerrarActionPerformed
        this.dispose();
        Login pLogin = new Login();
        pLogin.setVisible(true);
        pLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cerrarActionPerformed

    private void Btn_eliminar_predioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminar_predioActionPerformed
        this.dispose();
        EliminarPredio pEliPredio = new EliminarPredio();
        pEliPredio.setVisible(true);
        pEliPredio.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_eliminar_predioActionPerformed

    private void Btn_edit_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_edit_perfilActionPerformed
        String tipo_user = "Propietario";
        this.dispose();
        EditarPerfil pEditPer = new EditarPerfil(documentoPropietario, tipo_user);
        pEditPer.setVisible(true);
        pEditPer.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_edit_perfilActionPerformed

    private void Btn_edit_predioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_edit_predioActionPerformed
        this.dispose();
        Editar_predio EditPredio = new Editar_predio(documentoPropietario);
        EditPredio.setVisible(true);
        EditPredio.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_edit_predioActionPerformed

    private void Btn_ver_prediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ver_prediosActionPerformed
        this.dispose();
        Ver_predios VerPredios = new Ver_predios(documentoPropietario);
        VerPredios.setVisible(true);
        VerPredios.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_ver_prediosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Registro_predio;
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JButton Btn_edit_perfil;
    private javax.swing.JButton Btn_edit_predio;
    private javax.swing.JButton Btn_eliminar_predio;
    private javax.swing.JButton Btn_ver_predios;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
