/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
public class MenuFuncionario extends javax.swing.JFrame {
    private String documentoFuncionario;
    /**
     * Creates new form MenuFuncionario
     */
    public MenuFuncionario() {
        initComponents();
    }
    
    public MenuFuncionario(String documento) {
        this.documentoFuncionario = documento; // Almacenar el documento
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Registro_usuario_n = new javax.swing.JButton();
        Btn_ver_users = new javax.swing.JButton();
        Btn_edit_perfil = new javax.swing.JButton();
        Btn_cerrar = new javax.swing.JButton();
        Btn_ordenar_inspeccion = new javax.swing.JButton();
        Btn_ver_predios = new javax.swing.JButton();
        Btn_ver_lugares = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Btn_eliminar_user = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 112));
        jLabel1.setText("Bienvenido funcionario ICA");

        Btn_Registro_usuario_n.setBackground(new java.awt.Color(51, 153, 0));
        Btn_Registro_usuario_n.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Registro_usuario_n.setText("Registrar nuevo usuario");
        Btn_Registro_usuario_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registro_usuario_nActionPerformed(evt);
            }
        });

        Btn_ver_users.setBackground(new java.awt.Color(51, 153, 0));
        Btn_ver_users.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ver_users.setText("Ver usuarios registrados");
        Btn_ver_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ver_usersActionPerformed(evt);
            }
        });

        Btn_edit_perfil.setBackground(new java.awt.Color(51, 153, 0));
        Btn_edit_perfil.setForeground(new java.awt.Color(255, 255, 255));
        Btn_edit_perfil.setText("Editar perfil");
        Btn_edit_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_edit_perfilActionPerformed(evt);
            }
        });

        Btn_cerrar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cerrar.setText("Cerrar sesión");
        Btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cerrarActionPerformed(evt);
            }
        });

        Btn_ordenar_inspeccion.setBackground(new java.awt.Color(51, 153, 0));
        Btn_ordenar_inspeccion.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ordenar_inspeccion.setText("Ordenar inspecciones");
        Btn_ordenar_inspeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ordenar_inspeccionActionPerformed(evt);
            }
        });

        Btn_ver_predios.setBackground(new java.awt.Color(51, 153, 0));
        Btn_ver_predios.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ver_predios.setText("Ver predios");
        Btn_ver_predios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ver_prediosActionPerformed(evt);
            }
        });

        Btn_ver_lugares.setBackground(new java.awt.Color(51, 153, 0));
        Btn_ver_lugares.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ver_lugares.setText("Ver lugares de producción");
        Btn_ver_lugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ver_lugaresActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(51, 153, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Ver informe visita fitosanitaria");

        jButton11.setBackground(new java.awt.Color(51, 153, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Ver informe visita técnica");

        Btn_eliminar_user.setBackground(new java.awt.Color(51, 153, 0));
        Btn_eliminar_user.setForeground(new java.awt.Color(255, 255, 255));
        Btn_eliminar_user.setText("Eliminar usuario");
        Btn_eliminar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminar_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(Btn_ver_users, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(Btn_edit_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Registro_usuario_n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_eliminar_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_ordenar_inspeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_ver_predios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_ver_lugares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Registro_usuario_n)
                    .addComponent(Btn_ver_predios))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_ver_users)
                    .addComponent(Btn_ver_lugares))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_ordenar_inspeccion)
                    .addComponent(Btn_eliminar_user))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(Btn_edit_perfil))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(Btn_cerrar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Registro_usuario_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registro_usuario_nActionPerformed
        this.dispose();
        Registrar_nuevo_usuario pRegistro = new Registrar_nuevo_usuario(documentoFuncionario);
        pRegistro.setVisible(true);
        pRegistro.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_Registro_usuario_nActionPerformed

    private void Btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cerrarActionPerformed
        this.dispose();
        Login pLogin = new Login();
        pLogin.setVisible(true);
        pLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cerrarActionPerformed

    private void Btn_ordenar_inspeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ordenar_inspeccionActionPerformed
        this.dispose();
        Ordenar_inspeccion pOrden = new Ordenar_inspeccion(documentoFuncionario);
        pOrden.setVisible(true);
        pOrden.setLocationRelativeTo(null);

    }//GEN-LAST:event_Btn_ordenar_inspeccionActionPerformed

    private void Btn_eliminar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminar_userActionPerformed
       // Cierra esta ventana
        this.dispose();
        // Abre la otra ventana
        EliminarUser eliminar = new EliminarUser(documentoFuncionario);
        eliminar.setVisible(true);
        eliminar.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_eliminar_userActionPerformed

    private void Btn_edit_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_edit_perfilActionPerformed
        String tipo_user = "Funcionario ICA";
        this.dispose();
        EditarPerfil pEditPer = new EditarPerfil(documentoFuncionario, tipo_user);
        pEditPer.setVisible(true);
        pEditPer.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_edit_perfilActionPerformed

    private void Btn_ver_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ver_usersActionPerformed
        // Cierra esta ventana
        this.dispose();
        // Abre la otra ventana
        Ver_usuarios verU = new Ver_usuarios(documentoFuncionario);
        verU.setVisible(true);
        verU.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_ver_usersActionPerformed

    private void Btn_ver_prediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ver_prediosActionPerformed
        this.dispose();
        Ver_Predios_funcionarios VerPredios = new Ver_Predios_funcionarios(documentoFuncionario);
        VerPredios.setVisible(true);
        VerPredios.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_ver_prediosActionPerformed

    private void Btn_ver_lugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ver_lugaresActionPerformed
        String tipo_user = "Funcionario ICA";
        this.dispose();
        Ver_Lugares_funcionario pVerL = new Ver_Lugares_funcionario(documentoFuncionario, tipo_user);
        pVerL.setVisible(true);
        pVerL.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_ver_lugaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Registro_usuario_n;
    private javax.swing.JButton Btn_cerrar;
    private javax.swing.JButton Btn_edit_perfil;
    private javax.swing.JButton Btn_eliminar_user;
    private javax.swing.JButton Btn_ordenar_inspeccion;
    private javax.swing.JButton Btn_ver_lugares;
    private javax.swing.JButton Btn_ver_predios;
    private javax.swing.JButton Btn_ver_users;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
