/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
import logica.ControladorVerOrdenes; // Asegúrate de importar tu controlador
import logica.DatosOrden;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Ver_ordenes extends javax.swing.JFrame {
    private String documento;
    private final ControladorVerOrdenes controlador;
    /**
     * Creates new form Ver_ordenes
     */
    public Ver_ordenes() {
        initComponents();
        this.controlador = new ControladorVerOrdenes(); // Inicialización
        iniciarTabla();
    }
    
    public Ver_ordenes(String documento) {
        initComponents();
        this.documento = documento;
        this.controlador = new ControladorVerOrdenes(); // Inicialización
        iniciarTabla();
    }
    
    private void iniciarTabla() {
        // Por defecto, carga todos los Funcionarios ICA al iniciar
        cargarOrdenes(this.documento, "Tecnica");
    }
    
    private void cargarOrdenes(String doc, String tip) {
        List<DatosOrden> lista = controlador.buscarOrdenes(doc, tip);
        
        if (lista.isEmpty() && tip != null && !tip.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna orden de inspección de tipo " + tip + " con el documento " + doc, "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        } else if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ordenes pendientes de tipo " + tip, "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // Cargar el modelo de tabla con los datos
        DefaultTableModel modelo = controlador.cargarTablaOrdenes(lista);
        Tab_ordenes.setModel(modelo);
        
        // Ajustar el ancho de las columnas AHORA CON LAS 7 COLUMNAS NUEVAS
        if (Tab_ordenes.getColumnCount() > 0) {
            Tab_ordenes.getColumnModel().getColumn(0).setPreferredWidth(80); // Documento
            Tab_ordenes.getColumnModel().getColumn(1).setPreferredWidth(150);  // Nombre
            Tab_ordenes.getColumnModel().getColumn(2).setPreferredWidth(100);  // Apellido
            Tab_ordenes.getColumnModel().getColumn(3).setPreferredWidth(150); // Nombre de Usuario (Nuevo)
            Tab_ordenes.getColumnModel().getColumn(4).setPreferredWidth(200);  // Clave (Nueva)
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Btn_buscar8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_ordenes = new javax.swing.JTable();
        Btn_cancelar = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 112));
        jLabel1.setText("Mis Inspecciones pendientes");

        jLabel2.setText("Filtro por tipo:");

        Btn_buscar8.setBackground(new java.awt.Color(51, 153, 0));
        Btn_buscar8.setForeground(new java.awt.Color(255, 255, 255));
        Btn_buscar8.setText("Buscar");
        Btn_buscar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscar8ActionPerformed(evt);
            }
        });

        Tab_ordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tab_ordenes);

        Btn_cancelar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cancelar.setText("Cancelar");
        Btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cancelarActionPerformed(evt);
            }
        });

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnica", "Fitosanitaria" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(336, 336, 336)
                                    .addComponent(Btn_buscar8))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(153, 153, 153)
                                    .addComponent(Btn_cancelar)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(57, 57, 57)
                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Btn_buscar8)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_cancelar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_buscar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscar8ActionPerformed
        // 2. Obtener el documento a buscar
        String tipoInspeccion = (String) tipo.getSelectedItem();

        // 3. Determinar el argumento a pasar al método de carga
        String tipoFinal = null;
        if (!tipoInspeccion.isEmpty()) {
            tipoFinal = tipoInspeccion;
        }

        // 4. Llamar al método para cargar/actualizar la tabla
        cargarOrdenes(this.documento, tipoFinal);
    }//GEN-LAST:event_Btn_buscar8ActionPerformed

    private void Btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cancelarActionPerformed
        // Cierra esta ventana
        this.dispose();
        // Abre la otra ventana
        MenuTecnico menuTec = new MenuTecnico(this.documento);
        menuTec.setVisible(true);
        menuTec.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_ordenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_buscar8;
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JTable Tab_ordenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
