/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author CASA
 */
import logica.ControladorVerUsers; // Asegúrate de importar tu controlador
import logica.DatosUsuario2;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Ver_usuarios extends javax.swing.JFrame {
    private String documento;
    private final ControladorVerUsers controlador;
    /**
     * Creates new form Ver_usuarios
     */
    public Ver_usuarios() {
        initComponents();
        this.controlador = new ControladorVerUsers(); // Inicialización
        iniciarTabla(); // Llama a un nuevo método para la configuración inicial
    }
    
    public Ver_usuarios(String documento) {
        initComponents();
        this.documento = documento;
        this.controlador = new ControladorVerUsers(); // Inicialización
        iniciarTabla(); // Llama a un nuevo método para la configuración inicial
    }
    
    private void iniciarTabla() {
        // Por defecto, carga todos los Funcionarios ICA al iniciar
        cargarUsuarios((String) Seleccion_user.getSelectedItem(), null);
    }
    
    private void cargarUsuarios(String tipo, String doc) {
        List<DatosUsuario2> lista = controlador.buscarUsuarios(tipo, doc);
        
        if (lista.isEmpty() && doc != null && !doc.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró ningún usuario de tipo " + tipo + " con el documento " + doc, "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        } else if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay usuarios registrados de tipo " + tipo, "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // Cargar el modelo de tabla con los datos
        DefaultTableModel modelo = controlador.cargarTablaUsuarios(lista);
        Tab_users.setModel(modelo);
        
        // Ajustar el ancho de las columnas AHORA CON LAS 7 COLUMNAS NUEVAS
        if (Tab_users.getColumnCount() > 0) {
            Tab_users.getColumnModel().getColumn(0).setPreferredWidth(150); // Documento
            Tab_users.getColumnModel().getColumn(1).setPreferredWidth(100);  // Nombre
            Tab_users.getColumnModel().getColumn(2).setPreferredWidth(100);  // Apellido
            Tab_users.getColumnModel().getColumn(3).setPreferredWidth(100); // Nombre de Usuario (Nuevo)
            Tab_users.getColumnModel().getColumn(4).setPreferredWidth(100);  // Clave (Nueva)
            Tab_users.getColumnModel().getColumn(5).setPreferredWidth(150); // Email
            Tab_users.getColumnModel().getColumn(6).setPreferredWidth(150); // Info Adicional
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Seleccion_user = new javax.swing.JComboBox<>();
        Btn_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Txt_documento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_users = new javax.swing.JTable();
        Btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 112));
        jLabel1.setText("Usuarios registrados");

        jLabel2.setText("Filtro por tipo:");

        Seleccion_user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario ICA", "Productor", "Técnico", "Propietario" }));
        Seleccion_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccion_userActionPerformed(evt);
            }
        });

        Btn_buscar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Filtro por documento:");

        Tab_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tab_users);

        Btn_cancelar.setBackground(new java.awt.Color(51, 153, 0));
        Btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_cancelar.setText("Cancelar");
        Btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Seleccion_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(Btn_buscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Btn_cancelar)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Seleccion_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_buscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_cancelar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Seleccion_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccion_userActionPerformed
        
    }//GEN-LAST:event_Seleccion_userActionPerformed

    private void Btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cancelarActionPerformed
        // Cierra esta ventana
        this.dispose();
        // Abre la otra ventana
        MenuFuncionario menuF = new MenuFuncionario(this.documento);
        menuF.setVisible(true);
        menuF.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_cancelarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        // 1. Obtener el tipo de usuario seleccionado
        String tipoSeleccionado = (String) Seleccion_user.getSelectedItem();
        
        // 2. Obtener el documento a buscar
        String documentoBuscado = Txt_documento.getText().trim();
        
        // 3. Determinar el argumento a pasar al método de carga
        String documentoFinal = null;
        if (!documentoBuscado.isEmpty()) {
            documentoFinal = documentoBuscado;
        }
        
        // 4. Llamar al método para cargar/actualizar la tabla
        cargarUsuarios(tipoSeleccionado, documentoFinal);
    }//GEN-LAST:event_Btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_cancelar;
    private javax.swing.JComboBox<String> Seleccion_user;
    private javax.swing.JTable Tab_users;
    private javax.swing.JTextField Txt_documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
